### ISSUE TITLE
Uses insecure library for generating Bitcoin addresses

### ISSUE THREAD

**Issue by qirtaiba** [coinables/Bitcoin-NoAPI-Shopping-Cart#2]
A couple of people have experienced their Bitcoins vanishing when using addresses generated by the PHPCoinAddress.php library. See https://github.com/zamgo/PHPCoinAddress/issues/3. This doesn't inspire confidence. Possible that someone is generating the same private keys and sweeping up the coins?

**Comment by coinables** [comment]
ACK - Need to find a stand alone CPRNG PHP lib that can generate key pairs.

**Comment by Beetario** [comment]
Deberías borrar este proyecto de Github, todo el dinero se va a esta dirección https://blockchain.info/es/address/1JCuJXsP6PaVrGBk3uv7DecRC27GGkwFwE

**Comment by qirtaiba** [comment]
I'm going to post a pull request for the patch that fixed it for me.

**Comment by coinables** [comment]
@qirtaiba did you find a decent php library? I'm not working on this project anymore, but if someone is stealing funds based on PHPCoinAddress library then I'm going to delete the repo like @nelsonmurciia suggests.

**Comment by qirtaiba** [comment]
See #4.

**Comment by coinables** [comment]
This repo is now retired. Thank you for your contributions @qirtaiba @nelsonmurciia

**Comment by samirdjelal** [comment]
what do you mean by saying that somebody is stealing bitcoin using PHPCoinAddress?, if I used the official one can that happen too?
